safe: false
source: .
destination: ./_site
plugins_dir: ./_plugin
highlighter: rouge
markdown: kramdown
exclude: ['CNAME', 'Gemfile', 'Gemfile.lock', 'Rakefile', 'README.md', '.sass-cache', '_tr']

plugins:
  - jekyll-assets
  - jekyll-scholar
  - bootstrap

url: https://hydra-repo.io
baseurl: 

# Configuration for site
title: 
logo_title: 
author: 
email:
# logo: assets/img/logo.png

font-awesome:
  assets: true

# google_analytics:
#    account: UA-XXXXX-X

# # jekyll-scholar configurations
# scholar:
#   style: apa
#   locale: en
#   bibliography_template: pub

#   sort_by: year,month
#   order: descending

#   source: ./_publications
#   details_dir: assets/bibtex
#   details_layout: bib-item-details.html
#   details_link: BibTex
#   bibliography: '**/*.bib'

assets:
  compression: false
  digest: false
  sources:
    - _assets/scss
    - _assets/images
    - _assets/fonts
    - _assets/js
    - _assets/bower
    - _assets/misc
    - _assets/plugins/font-awsome
    - _assets/plugins/google-map
    - _assets/plugins/mixitup
    - _assets/plugins/jquery
    - _assets/plugins/magnific-popup
    - _assets/plugins/popper
    - _assets/plugins/slick
    - _assets/plugins/smoothscroll
    - _assets/plugins/syotimer
    
  # plugins:
  #   css:
  #     autoprefixer:
  #       browsers:
  #         - "last 2 versions"
  #         - "IE > 9"

  #   img: { optim: {}, magick: {} }
